### ISSUE TITLE
unable to add transport

### ISSUE THREAD

**Issue by afrozl** [vanthome/winston-elasticsearch#20]
Winston version 2.2.0

```
winston.add(winston.transports.Elasticsearch, esTransportOpts);
TypeError: transport is not a constructor
    at Logger.add (/elasticsearch/apps/synchrony/node_modules/winston/lib/winston/logger.js:475:41)
    at Object.winston.(anonymous function) [as add] (/elasticsearch/apps/synchrony/node_modules/winston/lib/winston.
js:87:34)
    at repl:1:9
    at defaultEval (repl.js:272:27)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at REPLServer.repl.eval (/usr/lib/node_modules/nesh/lib/plugins/doc.js:147:16)
    at REPLServer.<anonymous> (repl.js:441:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
    at REPLServer.Interface._onLine (readline.js:224:10)
    at REPLServer.Interface._line (readline.js:566:8)
    at REPLServer.Interface._ttyWrite (readline.js:843:14)
    at ReadStream.onkeypress (readline.js:115:10)
    at emitTwo (events.js:111:20)
    at ReadStream.emit (events.js:191:7)
```

**Comment by vanthome** [comment]
could you solve the problem? For me it works fine with winston 2.2.0

**Comment by phillipwei** [comment]
I'm seeing something similar. Using winston@2.3.0, instantiating with

```
winston.add(winston.transports.Elasticsearch,
  {
    clientOpts: {
      host: 'http://323144a4232224606fe794867adaa5e7.us-west-1.aws.found.io:9200'
    }
  }
);
```

Error I'm getting:
```
var instance = created ? transport : (new (transport)(options));
                                        ^
TypeError: transport is not a function
    at Logger.add (P:\Code\git\OpenInvestWeb\node_modules\winston\lib\winston\logger.js:481:41)
    at Object.winston.(anonymous function) [as add] (P:\Code\git\OpenInvestWeb\node_modules\winston\lib\winston.js:86:34)
    at Object.<anonymous> (P:\Code\git\OpenInvestWeb\app.js:75:9)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (P:\Code\git\OpenInvestWeb\bin\www:3:11)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by fernandoghisi** [comment]
Same error for me, with a simple DailyRotateFile (winston 2.3.1)

Code:
```
const logger = require('winston');
logger.add(logger.transports.DailyRotateFile, { filename: __dirname + '/logs/test.log' });
```
Error:
```
\node_modules\winston\lib\winston\logger.js:481
  var instance = created ? transport : (new (transport)(options));
                                        ^
TypeError: transport is not a constructor
    at Logger.add (C:\www\casan-mobile\casan-mobile-notifications-center\node_modules\winston\lib\winston\logger.js:481:41)
    at Object.winston.(anonymous function) [as add] (C:\www\casan-mobile\casan-mobile-notifications-center\node_modules\winston\lib\winston.js:86:34)
```

**Comment by fernandoghisi** [comment]
In fact, my code works with winston 1.1

**Comment by vanthome** [comment]
@fernandoghisi that has nothing to do with this transport as far as I can see.

**Comment by MirkoTV** [comment]
Any help on this one? same error trying to add an Elasticsearch transport

**Comment by vanthome** [comment]
@MirkoTV what version of Winston are you using? Obviously it works in the tests, just try to run them:

https://github.com/vanthome/winston-elasticsearch/blob/master/test/test.js#L48

**Comment by MirkoTV** [comment]
Thanks for answering @vanthome, I am using winston 2.3.0, I had installed winston long time ago, so not sure why but removing it and installing at the same time with winston-elasticsearch did the trick.

**Comment by vanthome** [comment]
👍
